### ISSUE TITLE
error during shop login

### ISSUE THREAD

**Issue by quantenschaum** [wellenvogel/ochartsng#14]
When trying to log in into the ocharts shop to update my charts, I get `Error: Code: 3n`.

It was working before (great feature by the way).

The login credentials are valid.

avnav: 20240708-0907
ochartsng: 20240616-raspbian-bullseye
on openplotter

**Comment by quantenschaum** [comment]
updating the chart manually (zip upload) does work.

**Comment by wellenvogel** [comment]
not sure what is wrong there.
The "3n" error is not really known. I will try to get in contact with o-charts about it.
